apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "mp4"
  MONGODB_URI: "mongodb://kakarot:goku2001@mongodb:27017/mp3s?authSource=admin" #nodeip:nodeport
